export const actionTypes = {
  FETCHING_START: "FETCHING_START",
  FETCHING_SUCCESS: "FETCHING_SUCCESS",
  FETCHING_ERROR: "FETCHING_ERROR",
  CART_OPEN: "CART_OPEN",
  CART_CLOSE: "CART_CLOSE",
  FILTER_OPEN: "FILTER_OPEN",
  FILTER_CLOSE: "FILTER_CLOSE",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_CART_FROM_DETAILS: "ADD_TO_CART_FROM_DETAILS",
  CART_ITEM_QTY_INCREASE: "CART_ITEM_QTY_INCREASE",
  CART_ITEM_QTY_DECREASE: "CART_ITEM_QTY_DECREASE",
  CART_ITEM_REMOVE: "CART_ITEM_REMOVE",
};
